server:
  port: 9009
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka
  instance:
    hostname: ${spring.cloud.client.ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
order-resources:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 10  # 熔断触发最小请求次数，默认值是20
        sleepWindowInMilliseconds: 3000  # 熔断后休眠时长，默认值5秒
        errorThresholdPercentage: 50 # 触发熔断错误比例阈值，默认值50%
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

logging:
  level:
    com.project: debug
ribbon:
  ConnectTimeout: 1000 # 连接超时时长
  ReadTimeout: 2000 # 数据通信超时时长
  MaxAutoRetries: 1 # 当前服务器的重试次数
  MaxAutoRetriesNextServer: 1 # 重试多少次服务
  OkToRetryOnAllOperations: true # 是否对所有的请求方式都重试
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
      min-request-size: 2048
      mime-types: text/html,application/xml,application/json # 设置压缩的数据类型
    response:
      enabled: true
